services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
  mongodb:
    image: mongo:8.0.9
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo_data:/data/db
    command: mongod --auth

  app:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - ./backend/.env     
    ports:
      - 8000:8000

volumes:
  qdrant_storage:
  mongo_data:

